#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname "${BASH_SOURCE}")" ; cd .. > /dev/null 2>&1 && pwd -P)"

source ~/.asdf/asdf.sh

source $PROJECT_DIR/.venv/bin/activate

export PYTHONPATH="$PROJECT_DIR/solaredge2mqtt:${PYTHONPATH:-}"
#export PYTHONPATH="$PROJECT_DIR/solaredge2mqtt"


python -m solaredge2mqtt "$@"


# vi: ft=sh
